services:
  # Copy file from host then install pnpm packages for frontend and backend together
  initializer:
    image: node:23
    container_name: hallucinet-initializer
    restart: on-failure
    volumes:
      - ./:/src/
      - hallucinet:/app/
    command: /bin/bash -c "
      cp /src/* /app/ -r &&

      npm install -g pnpm@latest &&
      echo '===== app/backend =====' &&
      cd /app/backend/ && pnpm install &&
      echo '===== app/frontend =====' &&
      cd /app/frontend/ && pnpm install
      "

  # Sync files from host to docker volume every 5 seconds so hot reloads work
  syncer:
    image: servercontainers/rsync
    container_name: hallucinet-syncer
    volumes:
      - ./:/src/
      - hallucinet:/app/
    command: /bin/bash -c "
      while true; do
      rsync -avch --exclude=node_modules/ --exclude=.next/ --exclude=.pnpm-store/ --cvs-exclude /src/ /app/ &&
      sleep 5;
      done;
      "
    depends_on:
      initializer:
        condition: service_completed_successfully

  backend:
    image: node:23
    container_name: hallucinet-backend
    restart: on-failure
    working_dir: /app/backend/
    environment:
      - APPWRITE_ENDPOINT=https://cloud.appwrite.io/v1
      - APPWRITE_PROJECT=67ef5621003d5fdb528d
      - APPWRITE_API_KEY=standard_514aa5990ecc11ddadafcc3ed108640b5804c3fd1b8572f5765975eccc219d4424ad0e6524a1a752d3da2ee3eb47d16a57c497c60417ec3d6a49cc38a1ca7c41abf24d8cea2046012b13a4f9ff309ea6f890558d0ed658ab9b04ae108ce51821068ef1619687c36a42e5d8d64a8877fab8aac08ff484d0c3466ace7d6b855b3d
      - APPWRITE_DATABASE_ID=67f756f80029d2037895
      - USER_COLLECTION_ID=6807322b000d51733ec0
      - TEAM_COLLECTION_ID=68073238001e53aa95d1
      - CONTAINER_COLLECTION_ID=68089d06003e1afa4d22
      - DEVICE_COLLECTION_ID=68089c7a0038a0ca0882
    volumes:
      - hallucinet:/app/
    command: /bin/bash -c "npm install -g pnpm@latest && pnpm run start:dev"
    depends_on:
      initializer:
        condition: service_completed_successfully

  frontend:
    image: node:23
    container_name: hallucinet-frontend
    restart: on-failure
    working_dir: /app/frontend/
    volumes:
      - hallucinet:/app/
    command: /bin/bash -c "npm install -g pnpm@latest && pnpm run dev"
    depends_on:
      initializer:
        condition: service_completed_successfully

  nginx:
    image: nginx:latest
    container_name: hallucinet-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      initializer:
        condition: service_completed_successfully

volumes:
  hallucinet:
