services:
  backend:
    image: node:23
    container_name: hallucinet-backend
    working_dir: /app
    volumes:
      - ./backend/:/app
    command: /bin/bash -c "npm install -g pnpm@latest && pnpm install && pnpm run start:dev"

  frontend:
    image: node:23
    container_name: hallucinet-frontend
    working_dir: /app
    volumes:
      - ./frontend/:/app
    command: /bin/bash -c "npm install -g pnpm@latest && pnpm install && pnpm run dev"

  nginx:
    image: nginx:latest
    container_name: hallucinet-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
