services:
  clientA:
    image: nicolaka/netshoot
    container_name: clientA
    networks:
      hallucinet-vpn:
        ipv4_address: 192.168.100.2
    volumes:
      - ./:/app/
      - .test/clientA.hallucinet.token:/root/.hallucinet/token
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
  clientB:
    image: nicolaka/netshoot
    container_name: clientB
    networks:
      hallucinet-vpn:
        ipv4_address: 192.168.100.3
    volumes:
      - ./:/app/
      - .test/clientB.hallucinet.token:/root/.hallucinet/token
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN

networks:
  hallucinet-vpn:
    ipam:
      config:
        - subnet: 192.168.100.0/24
